### ISSUE TITLE
Can not open table with primary key of type VarChar in utf8 format [ODBC124]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-odbc-driver#121]
Submitted by: Thomas Schwarzmüller (blacky)

Attachments:
[Firebird_ODBC_2.0.2.153_Win32.exe](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-124/12340_Firebird_ODBC_2.0.2.153_Win32.exe)
[Firebird_ODBC_2.0.2.153_x64.exe](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-124/12341_Firebird_ODBC_2.0.2.153_x64.exe)
[msaccess.patch](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-124/13181_msaccess.patch)

I like to open a Firebird Database with MS Access 2007\. The connection works\.
But when I open a table which primary key is of type VarChar, all data fields show "#&#x2060;deleted"\.
The database has utf8 format\. 
Error doesn't occur with:
\- Tables with non text primary keys\.
\- Databases with other text formats \(like ISO8859\_1\)

**Comment by MicheleFire2022** [comment]
> with this fix in attachment

I have the problem that MS Access show me all results deleted ... The Firebird server has UTF8 char set but i can't change this parameter

Br

**Comment by jabrugger** [comment]
@irodushka This issue still persists on 3.0.1 (22/dec/2023) build.
Would be great to get it fixed also.

**Comment by irodushka** [comment]
I understand right it's a legacy issue from the prod driver? I will take a
look tomorrow. If you can send me the faulty table structure ddl (create
table....), it will definitely help.
Regards.

пт, 22 дек. 2023 г., 18:40 jabrugger ***@***.***>:

**Comment by jabrugger** [comment]
Yes, the 2.0.5 build has this issue too.
Attached is a script which generates this issue when browsing the table from MS Access.
[Firebird ODBC #121.zip](https://github.com/FirebirdSQL/firebird-odbc-driver/files/13754463/Firebird.ODBC.121.zip)

**Comment by irodushka** [comment]
Hi
I made a fix in the last build, you can try it.
This version magically detects that it's loaded from MSAccess and applies a patch))) So you don't need a special ODBC driver build. Hope it will work ok.

**Comment by jabrugger** [comment]
@irodushka It seems to work fine! Thank you so much! 
If I find a problem I'll let you know.

**Comment by irodushka** [comment]
You're welcome!)

ср, 27 дек. 2023 г. в 16:56, jabrugger ***@***.***>:

**Comment by MicheleFire2022** [comment]
> Hi @jabrugger I made a fix in the last build, you can try it. This version magically detects that it's loaded from MSAccess and applies a patch))) So you don't need a special ODBC driver build. Hope it will work ok.

Hi ,  i also had the problem. Where can i find the last release with this patch? 
thanks :-)

**Comment by jabrugger** [comment]
@MicheleFire2022 it's available at https://github.com/FirebirdSQL/firebird-odbc-driver/wiki

**Comment by MicheleFire2022** [comment]
thanks a lot ;-)

**Comment by MicheleFire2022** [comment]
ah.... i have an old firebird so i can't use this one :-(

**Comment by mrotteveel** [comment]
> ah.... i have an old firebird so i can't use this one :-(

I assume it will work with an older Firebird, as long as you use a Firebird 3.0 or higher fbclient.dll.

**Comment by irodushka** [comment]
Closed
