### ISSUE TITLE
ODBC driver doesn't work in SSIS package on Win2012 Server 64-bit [ODBC164]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-odbc-driver#158]
Submitted by: Shakh Viktor (shakhviktor)

Votes: 1

I created SSIS package for loading data from Firebird 2\.5 table with field type varchar\(20\), charset win1251
to table on ms sql server with field type nvarchar\(20\)\.
ADO Net Source uses Firebird\_ODBC\_2\.0\.1\.152\_x64 driver, 
and OLE DB Destination uses Microsoft OLE DB Provider for SQL Server\.
The result of data flow task is empty field in the table on ms sql server side\.

**Comment by irodushka** [comment]
I don't think Win2012 Server is actual in 2024)
You may reopen it if needed.
