### ISSUE TITLE
Affected Rows always returns 0 [ODBC171]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-odbc-driver#163]
Submitted by: MT Jordan (mtjo62)

Attachments:
[test_firebird_odbc_aff_rows.php](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-171/12422_test_firebird_odbc_aff_rows.php)

I found a closed bug report for this same issue and I wanted to open a new report as this issue appears unresolved\. The PHP ODBC function odbc\_num\_rows\(\) always returns 0 for all update, insert and delete queries\. This only applies to the Firebird ODBC driver\. The standard and PDO PHP extensions return affected rows as expected\.

**Comment by irodushka** [comment]
Need to be tested on 3.0 driver

**Comment by irodushka** [comment]
I see it's working correct now. Please reopen if the problem persists.
