### ISSUE TITLE
ODBC driver is not compiled with Borland compiler [ODBC197]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-odbc-driver#183]
Submitted by: Dimitar Zhekov (sheckley)

Block progress on [ODBC198](https://github.com/FirebirdSQL/firebird-odbc-driver/issues?q=ODBC198+in%3Atitle)
Block progress on [ODBC200](https://github.com/FirebirdSQL/firebird-odbc-driver/issues?q=ODBC200+in%3Atitle)
Block progress on [ODBC199](https://github.com/FirebirdSQL/firebird-odbc-driver/issues?q=ODBC199+in%3Atitle)

Attachments:
[bcc55-compile-204.diff](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-197/12983_bcc55-compile-204.diff)
[bcc55-odbuild-204.diff](https://github.com/FirebirdSQL/jira-attachments/raw/main/ODBC/ODBC-197/12984_bcc55-odbuild-204.diff)

\.\.\.\\OdbcJdbc\\Builds\\Bcc55\.win\> buildNT\.bat C:\\Borland\\BCC55

MAKE Version 5\.2  Copyright \(c\) 1987, 2000 Borland
Error \.\./makefile\.environ 9: Command syntax error
Error \.\./makefile\.environ 11: Command syntax error
Error \.\./makefile\.environ 13: Command syntax error
Error \.\./makefile\.environ 15: Command syntax error
Error \.\./makefile\.environ 17: Command syntax error
\[\.\.\.\]
\*\*\* 31 errors during make \*\*\*

The problem is that "makefile\.bcc55", which is written for Borland make, includes "\.\./makefile\.environ", which is for GNU make\. So, neither the Borland nor the GNU make utilities will work\.

I can try to write a proper "makefile\.environ\-bcc" file, or however you wold prefer to call it\.

**Comment by irodushka** [comment]
Please let me know if the issue is still active or close it please.
Regards.
