### ISSUE TITLE
SQLGetData with zero-length BLOB

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird-odbc-driver#201]
If a BLOB contains zero-length data, SQLGetData() may return garbage on first call (if target is SQL_C_WCHAR) and surely return garbage instead of SQL_NO_DATA on second call (or even crash).

You can pick the fix from https://github.com/aafemt/firebird-odbc-driver/commit/387c1ab375812a0355e763e2f89835fe8b4758fc if you wish.

**Comment by irodushka** [comment]
>You can pick the fix from https://github.com/aafemt/firebird-odbc-driver/commit/387c1ab375812a0355e763e2f89835fe8b4758fc if you wish.

Patch applied to a beta-version branch (https://github.com/FirebirdSQL/firebird-odbc-driver/wiki)

**Comment by irodushka** [comment]
Closed
