### ISSUE TITLE
Support for WireCompression with ODBC 

### ISSUE THREAD

**Issue by bogdan-soare** [FirebirdSQL/firebird-odbc-driver#203]
Is there any way to implement WireCompression using the Firebird ODBC driver?
At the server I have set WireCompression=true in firebird.conf and I have restarted the service.
At the client I have set WireCompression=true in firebird.conf which is located in the same folder as fbclient.dll and zlib1.dll.

When connecting to the remote database through the ODBC driver, from Visual Fox Pro, I noticed that WireCompression is not used.
The connection string refers to the location of the fbclient.dll mentioned earlier.
The ODBC driver's version is 2.0.5.156.

**Comment by mrotteveel** [comment]
That would suggest that the ODBC driver is using a *different* `fbclient.dll` than the one that has the `firebird.conf` and `zlib1.dll`, or that the `fbclient.dll` and/or `zlib1.dll` is 64-bit instead of 32-bit (iirc FoxPro is 32-bit only).

**Comment by bogdan-soare** [comment]
You are right! I was using the _wrong_ zlib1.dll from the 64 bit install of the Firebird Server rather than the one from the 32 bit install. Now it works. Thanks a lot!
