### ISSUE TITLE
Configuration switch for WireCompression

### ISSUE THREAD

**Issue by MartinKoeditz** [FirebirdSQL/firebird-odbc-driver#204]
I'm missing a config switch to turn on wire compression. Is it already useable though connection params?

**Comment by mrotteveel** [comment]
The firebird-odbc-driver project currently has no active maintainer. 

The workaround is to make sure the fbclient.dll loaded by the driver can find zlib1.dll and its firebird.conf contains `WireCompression = true`.

**Comment by irodushka** [comment]
Hi @MartinKoeditz 

You mean - you need an option (checkbox) in ODBC DSN settings dialog window? and the corresponding opts in an ini file/Registry?

Regards

**Comment by balger** [comment]
In the current version 3.0.0.9 in the documentation or help there is no reference to the wirecompression parameter.
It would be a very good option

**Comment by irodushka** [comment]
Hi @balger 

You can try 3.0.0.10 build. I've added a compression option to a DSN dialog. It definitely works - you can check MON$WIRE_COMPRESSED field in MON$ATTACHMENTS to ensure.
Do not forget to put a zlib1.dll to appropriate place. If you're using 32 bit driver, you should copy a 32-bit zlib1.dll to Windows/SysWOW64, if you're using 64-bit driver - 64-bit version zlib1.dll to Windows/System32.

Regards

**Comment by irodushka** [comment]
>You can try 3.0.0.10 build - I mean https://github.com/FirebirdSQL/firebird-odbc-driver/wiki

**Comment by balger** [comment]
I appreciate your work very much. Thanks a lot.

    El sábado, 13 de abril de 2024, 15:42:55 ART, irodushka ***@***.***> escribió:  
 
 


Hi @balger

You can try 3.0.0.10 build. I've added a compression option to a DSN dialog. It definitely works - you can check MON$WIRE_COMPRESSED field in MON$ATTACHMENTS to ensure.
Do not forget to put a zlib1.dll to appropriate place. If you're using 32 bit driver, you should copy a 32-bit zlib1.dll to Windows/SysWOW64, if you're using 64-bit driver - 64-bit version zlib1.dll to Windows/System32.

Regards

**Comment by irodushka** [comment]
Try it first)))

**Comment by irodushka** [comment]
@balger 
oops... I've forgot to rebuild the installers.... wait a bit, I'll return back in 5 min)

**Comment by irodushka** [comment]
well, now it's ok

**Comment by irodushka** [comment]
Seems complete. Please open again if any problems occur.
