### ISSUE TITLE
ODBC - Firebird 4

### ISSUE THREAD

**Issue by Uzytkownik111** [FirebirdSQL/firebird-odbc-driver#205]
Hello,

I would like to ask if there are ODBC drivers for Firebird 4 ?

Regards 
U

**Comment by mrotteveel** [comment]
The firebird-odbc-driver project currently has no active maintainer. 

As far as I know, this driver should work with Firebird 4.0, if you're using table names shorter than 31 characters, and if you have `DataTypeCompatibility = 2.5` configured in firebird.conf.

There is also third-party, commercial, ODBC driver for Firebird, see https://www.devart.com/odbc/firebird/

**Comment by irodushka** [comment]
Hi @Uzytkownik111 !

You can try a beta-version -> https://github.com/FirebirdSQL/firebird-odbc-driver/wiki
It is not 100% tested, but it seems to work in general)

regards

**Comment by irodushka** [comment]
Closed.
3.0.0.* beta-version (https://github.com/FirebirdSQL/firebird-odbc-driver/wiki) supports FB4&5
