### ISSUE TITLE
Cannot link tables using MS Access

### ISSUE THREAD

**Issue by jabrugger** [FirebirdSQL/firebird-odbc-driver#210]
[SQL.LOG](https://github.com/FirebirdSQL/firebird-odbc-driver/files/13717305/SQL.LOG)
Using Firebird_ODBC_3.0.0.1_x64.exe release (dated 8/Dec/2023)

**Comment by jabrugger** [comment]
[SQL.LOG](https://github.com/FirebirdSQL/firebird-odbc-driver/files/13717249/SQL.LOG)
Using Firebird_ODBC_3.0.0.1_x64.exe release (dated 8/Dec/2023)

**Comment by irodushka** [comment]
Hi jabrugger!

Looking at your log:
```
SIPRES          10764-107dc	ENTER SQLExecDirectW 
		HSTMT               0x0000027FB10D21B0
		WCHAR *             0x00007FFF8EE587B0 [      -3] "SELECT Config, nValue FROM MSysConf\ 0"
		SDWORD                    -3

SIPRES          10764-107dc	EXIT  SQLExecDirectW  with return code -1 (SQL_ERROR)
		HSTMT               0x0000027FB10D21B0
		WCHAR *             0x00007FFF8EE587B0 [      -3] "SELECT Config, nValue FROM MSysConf\ 0"
		SDWORD                    -3

		DIAG [42S02] [ODBC Firebird Driver][Firebird]Dynamic SQL Error
-SQL error code = -204
-Table unknown
-MSYSCONF
-At line 1, column 28 (-204) 
...
		WCHAR *             0x0000027FB6E42120 [     119] "[ODBC Firebird Driver][Firebird]Dynamic SQL Error\ a-SQL error code = -204\ a-Table unknown\ a-MSYSCONF\ a-At line 1, column 28"
```

you have some garbage in the select statement - "SELECT Config, nValue FROM MSysConf**\ 0**", and this is probably the reason for the error.

Please check your MS Access project. If you think there is nothing wrong on your end, please tell me how I can reproduce this error.

Regards
Yuri

**Comment by irodushka** [comment]
Aha, sorry, your are right, I've just reproduced it. Will investigate.

**Comment by irodushka** [comment]
Hi
Just uploaded the patched driver to https://github.com/FirebirdSQL/firebird-odbc-driver/wiki
Seems it will work with MSAccess properly)
If you could spend some of your time testing it, I would greatly appreciate it.
Regards

**Comment by jabrugger** [comment]
It seems to be resolved. Thank you.
