### ISSUE TITLE
Installer does not overwrite older DLLs

### ISSUE THREAD

**Issue by jabrugger** [FirebirdSQL/firebird-odbc-driver#211]
The installer should overwrite/replace older versions of FirebirdODBC.dll, but it doenst.

**Comment by irodushka** [comment]
This is because last time I did not update the dll version)) and InnoSetup did not see the point in replacing it) will fix it in the next patch.

**Comment by irodushka** [comment]
Fixed

**Comment by irodushka** [comment]
@jabrugger 
Please close this issue if it's not actual/fixed.
Regards
