### ISSUE TITLE
Windows defender warns malware in installers.zip 

### ISSUE THREAD

**Issue by tomneko** [FirebirdSQL/firebird-odbc-driver#212]
Windows defender warns 2 malware in installers.zip. I cant install this.

![スクリーンショット 2023-12-25 181307](https://github.com/FirebirdSQL/firebird-odbc-driver/assets/128874/7d57a3d3-6bb6-4e32-81b0-28ce84711a63)

**Comment by irodushka** [comment]
Hi

A separate scan of the installer binaries does not detect any malware.
I've just started a full scan of all my hosts & HDDs - well, that'll take a while) 

But I'm 99% sure it's a FP - follow these links:

- https://stackoverflow.com/questions/68834409/program-installed-with-inno-setup-seen-as-trojan-wacatac-bml
- https://github.com/felicienfrancois/node-innosetup-compiler/issues/10
- https://forum.avast.com/index.php?topic=28890.0
- +100500 others

I'm definitely using INNO Setup v6.22 to build installers. I may try using some ancient version of INNO Setup, such as 6.0.2 or earlier. Maybe it will help.

**Comment by jabrugger** [comment]
You can submit the installers to https://www.microsoft.com/en-us/wdsi/filesubmission so Windows Defender is trained.

**Comment by irodushka** [comment]
That's quite a long story))
I've changed InnoSetup from 6.2.2 to 5.6.1 and VirusTotal is silent now.
The new installer pack is on the wiki.

**Comment by irodushka** [comment]
@tomneko 
Please close this issue if it's not actual/fixed.
Regards

**Comment by tomneko** [comment]
Thanks and sorry this delay.
