### ISSUE TITLE
DECFLOAT not support

### ISSUE THREAD

**Issue by Zeki-Gursoy** [FirebirdSQL/firebird-odbc-driver#214]
I get "not yet implemented" error. I think ODBC driver 3 can't support DECFLOAT data type. When support it?

**Comment by irodushka** [comment]
@Zeki
You're quite right, it doesn't. In 2024 I hope, asap)
Regards and Happy NY

сб, 30 дек. 2023 г., 00:15 Zeki ***@***.***>:

**Comment by irodushka** [comment]
Hi @Zeki-Gursoy , @mariuz 

You can try 3.0.0.8 build -> https://github.com/FirebirdSQL/firebird-odbc-driver/wiki

New FB4+ types are supported in compatibility mode:
1. int128-like types are treated as varchars
2. decfloat types - as double precision (with possible precision loss)
3. with timezone - as without timezone

I will think about native support in the future, but now it's the only way to get a quick win.
Regards

**Comment by irodushka** [comment]
If your question is  "why the type is string", the answer is - cause int128-like types are treated as varchars.
I'm 99% sure that fmtBcd resolves to Numeric or Decimal with size > 18.

**Comment by samihanhikoski** [comment]
Seems to be int128, so ignore my comment. Works nicely as varchar

**Comment by irodushka** [comment]
Be sure, I greatly appreciate any  comments and wishes!

Btw I can interpret int128 as bigint (int64), but this will result in
overflow errors if the values does not fit to int64.



пн, 19 февр. 2024 г., 18:57 Sami Hanhikoski ***@***.***>:

**Comment by Zeki-Gursoy** [comment]
Dear @irodushka, now works. Thank you for this ODBC driver.

`select
	cast(123 as int128) "new int128",
	cast('123.45' as DECFLOAT(34)) "new decfloat",
	cast(current_timestamp as timestamp with time zone) "new timezone"
from rdb$database`

![resim](https://github.com/FirebirdSQL/firebird-odbc-driver/assets/30706420/89b3f7d7-e26b-4854-805b-f3bc41440b88)

**Comment by irodushka** [comment]
@Zeki-Gursoy , @samihanhikoski 

Can you please take a look at the 3.0.0.9 build? I've added a compatibility binds settings to the DSN setup dialog (for windows)
It looks like:
![image](https://github.com/FirebirdSQL/firebird-odbc-driver/assets/1415214/84535bd8-e02c-47d3-9217-22c37292ca04)

If you check the "Enable FB4+ compatibility mode" box, there are 2 options:

- If "Set bind" text field is empty, the default rules are applied (int128 to varchar;decfloat to legacy;time zone to legacy)
- If "Set bind" text field is NOT empty, it must contain your custom binding settings - for example, "int128 to bigint", or "int128 to double precision; decfloat to numeric"

If the "Enable FB4+ compatibility mode" box is NOT checked, all the types are processed in the native mode and you may engage the incompatibility/not support issues working with the new FB4+ types.

These settings affects FB4+ connections only. If you're connecting to FB3 or older, they make no sense at all.

Regards

**Comment by Zeki-Gursoy** [comment]
@irodushka, I tested with Excel external data query.
This is working, too. Even "Set Bind" box is empty but, "Enabled" checked. If unchecked, "not yet implemented" message.

I think, driver completed succesfully.
