### ISSUE TITLE
Update from 2.5 ODBC to 3.0 ERROR in excel with query. Dynamic SQL Error -SQL error code = -303 

### ISSUE THREAD

**Issue by pinkshole** [FirebirdSQL/firebird-odbc-driver#228]
Hello,

From working excel with ODBC 2.5, upgrade to ODBC 3.0 results in Dynamic SQL Error -SQL error code = -303. Thanks in advanced
![Captura de pantalla 2024-09-18 110820](https://github.com/user-attachments/assets/d74b3b0d-8010-48c5-ae5c-4d63a8c97e50)

**Comment by irodushka** [comment]
Hi @pinkshole 

I need you database (with appropriate data, maybe script to create table(s) and fill them) and the query you're running in excel to investigate it. 
What I see in your screenshot is a native FB server-side error, it could be caused by 100500 reasons...

Regards

**Comment by pinkshole** [comment]
Hi @irodushka,

Now is working!, with forced cast to decimal(15,3) in a calculated column of SQL. Thanks

**Comment by irodushka** [comment]
@pinkshole great, especially considering that I didn't do anything)))

However you're welcome to send me the details of your issues if you want me to check for any odbc driver problems related to your case.
