### ISSUE TITLE
Abnormal termination in SQLFetch()

### ISSUE THREAD

**Issue by fdcastel** [FirebirdSQL/firebird-odbc-driver#229]
Trying to use [odbc2parquet](https://github.com/pacman82/odbc2parquet) to fetch `RDB$RELATIONS` from a Firebird database halts the program during a `SQLFetch()` call.

![sqlfetch-halt](https://github.com/user-attachments/assets/844136d5-2f19-4b99-b359-0a1cd596c52f)

No other log or debug information is provided. 

A previous conversation about this problem with odbc2parquet author can be found [here](https://github.com/pacman82/odbc2parquet/issues/640#issuecomment-2371686209).

Command line to reproduce (Powershell)

```powershell
./odbc2parquet.exe -vvv query --connection-string "Driver={Firebird ODBC Driver};Database=/db/test.fdb;UID=SYSDBA;PWD=masterkey;" --column-length-limit 65535 /temp/relations.parquet  'SELECT * FROM rdb$relations;'
```

Environment:
- Firebird ODBC driver 3.0.0.11
- Firebird RDBMS 3.0.12.33787
- odbc2parquet v6.1.0
- Windows 11 Build 22621

**Comment by irodushka** [comment]
Hmm, interesting. I will take a look soon.

ср, 25 сент. 2024 г., 21:13 F.D.Castel ***@***.***>:

**Comment by fdcastel** [comment]
Thank you @irodushka. Build 3.0.0.12 fixed the problem. 👍🏻🚀😄

**Comment by irodushka** [comment]
@fdcastel thank you for testing) this bug was not covered by any of  the existing tests.
