### ISSUE TITLE
Unstable operation with a large number of connections

### ISSUE THREAD

**Issue by NickNevzorov** [FirebirdSQL/firebird-odbc-driver#236]
Hi!

I have a large project (Delphi XE3 + ADO), after upgrade Firebird to 3.0 I saw problems with the application. 

I localized the problem, on some clients' servers and locally I have the following: creating connections to the database works unstable with increasing load.

Simple code in C#, create 1000 connections to DB simultaneously:

```
using FirebirdSql.Data.FirebirdClient;
using System;
using System.Collections.Generic;
using System.Data.Odbc;

namespace Program
{

    class Program
    {

        static void Main(string[] args)
        {

            /* // Testing Firebird native
            List<FbConnection> fbList = new List<FbConnection>();
            for (int i = 1; i <= 1000; i++)
            {
                try
                {

                    var connection = new FbConnection("User=SYSDBA;Password=masterkey;Database=localhost/3053:c:\\rollcontrol\\rollcontrol;Pooling=false; MinPoolSize=0;MaxPoolSize=2000");
                    connection.Open();

                    fbList.Add(connection);
                    Console.WriteLine("FbConnection " + i.ToString());

                }
                catch (Exception e)
                {
                    Console.WriteLine(DateTime.Now.ToString() + ": " + e.ToString());
                }
            }*/

            List<OdbcConnection> odbcList = new List<OdbcConnection>();
            for (int i = 1; i <= 1000; i++)
            {
                try {

                    OdbcConnection DbConnection = new OdbcConnection("DSN=rollcontrol");
                    DbConnection.Open();

                    odbcList.Add(DbConnection);
                    Console.WriteLine("OdbcConnection " + i.ToString());

                } catch (Exception e) { 
                    Console.WriteLine(DateTime.Now.ToString() + ": " + e.ToString());
                }
            }

            Console.ReadKey();

        }

    }
}

```

ODBC driver settings:

![DNS](https://github.com/user-attachments/assets/8170e849-eabc-453d-b9ea-f4495ca1571d)

This code working stable on several computers, on some computers not working in general, on my development PC working unstable.

For example, x32, Firebird 3.0, ODBC driver 3.0.15:

![ODBC](https://github.com/user-attachments/assets/da281eb0-fe6a-4670-b04f-73d5f688c7a7)

System event log show exception Complus:

```
Система вызвала пользовательский компонент, а он дал сбой и создал исключение. Это свидетельствует об ошибке в компоненте. Уведомите об этом разработчика компонента и сообщите следующие сведения.
Код программы компонента: 2[ODBC][Env 018B04D0]
Имя метода: IDispenserDriver::CreateResource
Имя процесса: FirebirdODBC.exe
Исключение: c0000005
Адрес: 0X57370452
```

Program raise an exception and freezes (may work well, may no exception and freeze). In x64 freezes without exception.

I testes Firebird 2.5 + ODBC 2.0, Firebird 3.0 + ODBC 2.0, Firebird 3.0 + ODBC 3.0, all working unstable.

I tested ODBC connection with MS SQL Server, all working well.

Thanks

**Comment by NickNevzorov** [comment]
I have been create virtual machine to demonstrate the problem. Windows 10, latest  Firebird 3.0 + ODBC driver 3.0.15, Visual Studio 2022 + test project, running in VirtualBox 7: https://gofile.me/6Z5SR/I6cyhDP8t (vhd, 30GB)

By default target is x64, app freezing on 180 connections. On x32 program working, but raised exceptions:

![vm](https://github.com/user-attachments/assets/87aa09b7-b3f3-4136-b626-4afbc44e07f7)

**Comment by irodushka** [comment]
Hi @NickNevzorov 

>after upgrade Firebird to 3.0

You mean - upgrading FB server to ver3, or upgrading the ODBC driver?

>I testes Firebird 2.5 + ODBC 2.0, Firebird 3.0 + ODBC 2.0, Firebird 3.0 + ODBC 3.0, all working unstable.

Do I understand right it does not depend on ODBC or FB-server version?
Or does the problem only occur when using the ODBC 3.0 driver?
Do I understand right that the problem occures when you just make a connections to DB, without any sql queries or smth?
And what FB do you use - Classic or Superserver?

Unfortunately I will be absent till the end of the year, so I won't be able to investigate your ticket until Jan 2025.
To save a bit of time, you could try writing a test, using not ODBC, but the native FB API, to open these connections and see if it works or not? From the description I'm not shure if this is related to ODBC driver...

BTW you can write in Russian)

Regards

**Comment by NickNevzorov** [comment]
@irodushka Добрій день!

Есть приложение на Delphi XE3 (TAdoConnection + ODBC), уже более 5 лет работающее на Firebird 2.5.9 + ODBC 2.0, обслуживание запросов оборудования логистики складов.

В данный момент запускается новый объект, я решил обновить Firebird (2млрд. транзакций в версии 2.5 стало маловато, менее чем за год работы наступает необходимость перепаковки базы).  Поставил Firebird 5.0 + драйвер ODBC оставил 2.0. База примитивная, 4 таблицы, никаких хранимых процедур. Особенность работы в том, что на каждый запрос от оборудования создается новый поток, который подключается к базе данных и делает уже SQL запрос, в результате получаем большое количество одновременных подключений и запросов к БД (при нагрузке бывает 50-100 соединений).

Ну и собственно решил проверить как оно работает на новом сервере БД под большой нагрузкой, программа создает 500 потоков, в каждом потоке подключение к БД, потоки запускаются одновременно. В результате получил зависание приложения почти в 100% случаях (на x64). 

Причина была найдена - зависает установка соединения с базой данных в новом созданном потоке. Далее взял дополнительно Visual Studio, новый проект на C# для локализации проблемы:

1. Работа с нативными компонентами проблем не вызывает (FBConnection на c#, TIBDataBase на Delphi). Без проблем создаются около 5000 соединений, нет ни ошибок, ни исключений). Firebird использовал только x64 SuperServer всех возможных версий
2. При работе через ODBC ни версия Firebird (пробовал 2.5/3.0/4.0/5.0), ни версия ODBC драйвера (2.0/3.0) на проблему не влияет. Единственное при x32 возникающее исключение влияет только на текущий поток и приложение работает дальше, а в x64 зависает все. Firebird сервер при этом работает, если при зависшем приложении запустить вторую копию, то копия работает (ну и потом тоже зависает).
3. Стабильности нет, что локально, что на серверах клиентов, тест может отработать корректно, а может нет (чаще нет). В случае x32 "крашится" только поток, создающий проблемное соединение, в системном журнале событий ошибка Complus, выше код прикладывал. При х64 если запускать потомки одновременно, то виснет все не просто так, а забирая все ресурсы процессора, задачу снять при этом проблематично становится
4. Соединение с MSSQL сервером через ODBC я проверял в данных условиях, оно тоже работает без ошибок

**Comment by irodushka** [comment]
@NickNevzorov 

Видимо, какое-то дремучее легаси...
Вам спасибо) здорово, когда пользователи сами находят и исправляют баги))

Если это работает, не затруднит сделать веточку и PR  в master, я приеду и волью.

**Comment by NickNevzorov** [comment]
@irodushka сделал. 

Я также пересобрал драйвер 2.0 на основе последнего дистрибутива 2.0.5 + vc2022, хоть и написано что Firebird 3+ требует ODBC драйвер 3.0, у меня работает и с драйвером 2.0 нормально. Чуть позже залью ODBC драйвер 2.0 на гитхаб

**Comment by irodushka** [comment]
Ok ok. I really didn’t expect this topic to generate so much interest)

I will get back from vacation and investigate what's going on. Think that
truncation is not normal.


вт, 17 дек. 2024 г., 13:08 Mark Rotteveel ***@***.***>:

**Comment by mrotteveel** [comment]
> I will get back from vacation and investigate what's going on. Think that truncation is not normal.

In this case it is, because for admin users, `isc_info_user_names` will report the username of each attachment to the current database in the current process, so if you're using SuperServer or SuperClassic, and there are a lot of connections, the response will be truncated. Moving `isc_info_user_names` last (before `isc_info_end`) should at least prevent the truncation from not reporting other info items.

**Comment by irodushka** [comment]
Oh my Lord, what a case))))
@NickNevzorov, and you use SYSDBA for all those 100500 connections?
The easiest workaround is to use some non-admin users.

Another obvious fix in FB server is to reduce the username list (remove dups). I don't think it makes any sense to send just the same username 1000 times. But this is clearly not the right chat to discuss FB server patches.

**Comment by mrotteveel** [comment]
> Oh my Lord, what a case)))) @NickNevzorov, and you use SYSDBA for all those 100500 connections? The easiest workaround is to use some non-admin users.
> 
> Another obvious fix in FB server is to reduce the username list (remove dups). I don't think it makes any sense to send just the same username 1000 times. But this is clearly not the right chat to discuss FB server patches.

I already reported that as https://github.com/FirebirdSQL/firebird/issues/8353. However, in this case, as it will simply take the first returned username, the truncation is not a big problem.

**Comment by irodushka** [comment]
Seems it's ok with this PR.
The one more thing -
@NickNevzorov, can you please increase the buffer size here
```
	char result [2048];
```
to 65536? This will reduce the chance of truncation for scenarios not so extreme as yours)

**Comment by irodushka** [comment]
Ok, let it be(c)
