### ISSUE TITLE
ODBC Statements do not respect the driver SQL_ATTR_MAX_ROWS setting. [ODBC74]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-odbc-driver#73]
Submitted by: Clinton L. Warren (justdoro)

The driver does not respect the SQL\_ATTR\_MAX\_ROWS setting\.

Select a table with n rows \(say, 100\)\.

Create a select statement that has its SQL\_ATTR\_MAX\_ROWS setting set to 10 rows\.

Executing the select will return all 100 rows\.

Similar tests against the SQL Server ODBC driver and the MySQL ODBC driver return 10 rows\.

**Comment by irodushka** [comment]
The patch is fine, merged, thank you!
